version: "2"

linters:
  enable:
    - errcheck
    - err113
    - exhaustive
    - forbidigo
    - funcorder
    - gosec
    - revive
    - govet
    - ineffassign
    - staticcheck
    - unused
    - paralleltest
    - testifylint
    - thelper
    - sloglint
  exclusions:
    rules:
      - linters:
          - err113
        text: "do not define dynamic errors, use wrapped static errors instead"
      - linters:
          - revive
        text: "package comment should be of the form"
