// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package networkconfig_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileReader creates a new instance of MockFileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileReader {
	mock := &MockFileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileReader is an autogenerated mock type for the FileReader type
type MockFileReader struct {
	mock.Mock
}

type MockFileReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileReader) EXPECT() *MockFileReader_Expecter {
	return &MockFileReader_Expecter{mock: &_m.Mock}
}

// ReadFile provides a mock function for the type MockFileReader
func (_mock *MockFileReader) ReadFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReader_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileReader_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFileReader_Expecter) ReadFile(path interface{}) *MockFileReader_ReadFile_Call {
	return &MockFileReader_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockFileReader_ReadFile_Call) Run(run func(path string)) *MockFileReader_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileReader_ReadFile_Call) Return(bytes []byte, err error) *MockFileReader_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileReader_ReadFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockFileReader_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePath provides a mock function for the type MockFileReader
func (_mock *MockFileReader) ValidatePath(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReader_ValidatePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePath'
type MockFileReader_ValidatePath_Call struct {
	*mock.Call
}

// ValidatePath is a helper method to define mock.On call
//   - path string
func (_e *MockFileReader_Expecter) ValidatePath(path interface{}) *MockFileReader_ValidatePath_Call {
	return &MockFileReader_ValidatePath_Call{Call: _e.mock.On("ValidatePath", path)}
}

func (_c *MockFileReader_ValidatePath_Call) Run(run func(path string)) *MockFileReader_ValidatePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileReader_ValidatePath_Call) Return(err error) *MockFileReader_ValidatePath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReader_ValidatePath_Call) RunAndReturn(run func(path string) error) *MockFileReader_ValidatePath_Call {
	_c.Call.Return(run)
	return _c
}
